### ISSUE TITLE
How do I launch demo app?

### ISSUE THREAD

**Issue by xtotdam** [zostera/django-bootstrap4#151]
Please, provide instructions how to launch demo app

**Comment by MarvinKweyu** [comment]
1. Create a virtual environment.
2. Clone the repository to your local machine
3. run `pip install -r requirements.txt`.
4. In your terminal: `python manage.py runserver`

**Comment by xtotdam** [comment]
Thank you! Unfortunately, the demo app does not work.

```
(bs4) ...\django-bootstrap4> conda list
# packages in environment at C:\Miniconda3\envs\bs4:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
babel                     2.7.0                      py_0    conda-forge
beautifulsoup4            4.8.0                    py36_0    conda-forge
certifi                   2019.6.16                py36_1    conda-forge
django                    2.2.3                    py36_0    conda-forge
docutils                  0.14                  py36_1001    conda-forge
imagesize                 1.1.0                      py_0    conda-forge
jinja2                    2.10.1                     py_0    conda-forge
markupsafe                1.0                      py36_0    conda-forge
packaging                 19.0                       py_0    conda-forge
pip                       19.1.1                   py36_0    conda-forge
pygments                  2.4.2                      py_0    conda-forge
pyparsing                 2.4.1                      py_0    conda-forge
python                    3.6.7             he025d50_1005    conda-forge
pytz                      2019.1                     py_0    conda-forge
requests                  2.13.0                   py36_0    conda-forge
setuptools                41.0.1                   py36_0    conda-forge
six                       1.12.0                py36_1000    conda-forge
snowballstemmer           1.9.0                      py_0    conda-forge
soupsieve                 1.9.2                    py36_0    conda-forge
sphinx                    2.1.2                      py_0    conda-forge
sphinx_rtd_theme          0.4.3                      py_0    conda-forge
sphinxcontrib-applehelp   1.0.1                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.1                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.2                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.2                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.1                      py_0    conda-forge
sqlparse                  0.3.0                      py_0    conda-forge
wheel                     0.33.4                   py36_0    conda-forge
wincertstore              0.2                   py36_1002    conda-forge

(bs4) ...\django-bootstrap4> python manage.py runserver
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Miniconda3\envs\bs4\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Miniconda3\envs\bs4\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Miniconda3\envs\bs4\lib\site-packages\django\utils\autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "C:\Miniconda3\envs\bs4\lib\site-packages\django\core\management\commands\runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "C:\Miniconda3\envs\bs4\lib\site-packages\django\utils\autoreload.py", line 77, in raise_last_exception
    raise _exception[1]
  File "C:\Miniconda3\envs\bs4\lib\site-packages\django\core\management\__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Miniconda3\envs\bs4\lib\site-packages\django\utils\autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "C:\Miniconda3\envs\bs4\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Miniconda3\envs\bs4\lib\site-packages\django\apps\registry.py", line 122, in populate
    app_config.ready()
  File "C:\Miniconda3\envs\bs4\lib\site-packages\django\contrib\admin\apps.py", line 24, in ready
    self.module.autodiscover()
  File "C:\Miniconda3\envs\bs4\lib\site-packages\django\contrib\admin\__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "C:\Miniconda3\envs\bs4\lib\site-packages\django\utils\module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "C:\Miniconda3\envs\bs4\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Miniconda3\envs\bs4\lib\site-packages\django\contrib\gis\admin\__init__.py", line 5, in <module>
    from django.contrib.gis.admin.options import GeoModelAdmin, OSMGeoAdmin
  File "C:\Miniconda3\envs\bs4\lib\site-packages\django\contrib\gis\admin\options.py", line 2, in <module>
    from django.contrib.gis.admin.widgets import OpenLayersWidget
  File "C:\Miniconda3\envs\bs4\lib\site-packages\django\contrib\gis\admin\widgets.py", line 3, in <module>
    from django.contrib.gis.gdal import GDALException
  File "C:\Miniconda3\envs\bs4\lib\site-packages\django\contrib\gis\gdal\__init__.py", line 28, in <module>
    from django.contrib.gis.gdal.datasource import DataSource
  File "C:\Miniconda3\envs\bs4\lib\site-packages\django\contrib\gis\gdal\datasource.py", line 39, in <module>
    from django.contrib.gis.gdal.driver import Driver
  File "C:\Miniconda3\envs\bs4\lib\site-packages\django\contrib\gis\gdal\driver.py", line 5, in <module>
    from django.contrib.gis.gdal.prototypes import ds as vcapi, raster as rcapi
  File "C:\Miniconda3\envs\bs4\lib\site-packages\django\contrib\gis\gdal\prototypes\ds.py", line 9, in <module>
    from django.contrib.gis.gdal.libgdal import GDAL_VERSION, lgdal
  File "C:\Miniconda3\envs\bs4\lib\site-packages\django\contrib\gis\gdal\libgdal.py", line 48, in <module>
    lgdal = CDLL(lib_path)
  File "C:\Miniconda3\envs\bs4\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] Module not found
```

**Comment by xtotdam** [comment]
This environment was created using `conda env create -f=requirements.txt -n bs4` like 15 minutes ago

**Comment by MarvinKweyu** [comment]
You could try [this](https://github.com/openslide/openslide-winbuild/issues/18) or [this](https://stackoverflow.com/questions/52381275/oserror-winerror-126-the-specified-module-could-not-be-found-while-importin) solutions and let me know how it goes

**Comment by peopzen** [comment]
I just thought it was easy to launch the demo following the above steps. Unfortunately, I got problem:
django.core.exceptions.ImproperlyConfigured: Could not find the GDAL library (tried "gdal", "GDAL", "gdal2.2.0", "gdal2.1.0", "gdal2.0.0", "gdal1.11.0", "gdal1.10.0", "gdal1.9.0"). Is GDAL
installed? If it is, try setting GDAL_LIBRARY_PATH in your settings.
Any idea about this issue? Run on Ubuntu18.04, py36, django2.1.
Insetting file there is ""django.contrib.gis"", why do we need it in such a bootstrap app? GDAL seems related to Geo package.

**Comment by MarvinKweyu** [comment]
I could guess that it is needed to style the layout of the page the map was rendered on if anyone who was using the `django-bootstrap4` as an eternal package to reduce the load of writing everything.
Have you tried a `sudo apt-get install gdal-bin` ?

**Comment by dyve** [comment]
Hi all, the gis part is for the demo app. I can imagine it's not for everybody, might be good to make that optional.

**Comment by dyve** [comment]
The gis requirements for the demo (now: example) app were removed in 207ab33427aa7ebb64334b3020cd509c8dd4faa9. Thanks for reporting this.
