### ISSUE TITLE
Cannot run example

### ISSUE THREAD

**Issue by morenoh149** [zostera/django-bootstrap4#197]
I followed the instructions at https://github.com/zostera/django-bootstrap4/tree/master/example

I get error
```
$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/harrymoreno/.asdf/installs/python/3.7.3/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line                                                 
    utility.execute()
  File "/Users/harrymoreno/.asdf/installs/python/3.7.3/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute                                                                   
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/harrymoreno/.asdf/installs/python/3.7.3/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv                                                                 
    self.execute(*args, **cmd_options)
  File "/Users/harrymoreno/.asdf/installs/python/3.7.3/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute                                                                       
    output = self.handle(*args, **options)
  File "/Users/harrymoreno/.asdf/installs/python/3.7.3/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped                                                                        
    res = handle_func(*args, **kwargs)
  File "/Users/harrymoreno/.asdf/installs/python/3.7.3/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 87, in handle                                                             
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/Users/harrymoreno/.asdf/installs/python/3.7.3/lib/python3.7/site-packages/django/db/migrations/executor.py", line 18, in __init__                                                                     
    self.loader = MigrationLoader(self.connection)
  File "/Users/harrymoreno/.asdf/installs/python/3.7.3/lib/python3.7/site-packages/django/db/migrations/loader.py", line 49, in __init__                                                                       
    self.build_graph()
  File "/Users/harrymoreno/.asdf/installs/python/3.7.3/lib/python3.7/site-packages/django/db/migrations/loader.py", line 212, in build_graph                                                                   
    self.applied_migrations = recorder.applied_migrations()
  File "/Users/harrymoreno/.asdf/installs/python/3.7.3/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 73, in applied_migrations                                                           
    if self.has_table():
  File "/Users/harrymoreno/.asdf/installs/python/3.7.3/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 56, in has_table                                                                    
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/Users/harrymoreno/.asdf/installs/python/3.7.3/lib/python3.7/site-packages/django/db/backends/base/base.py", line 256, in cursor                                                                       
    return self._cursor()
  File "/Users/harrymoreno/.asdf/installs/python/3.7.3/lib/python3.7/site-packages/django/db/backends/dummy/base.py", line 20, in complain                                                                     
    raise ImproperlyConfigured("settings.DATABASES is improperly configured. "
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.  
```

**Comment by SarathVakacharla** [comment]
update _DATABASES_ in _settings.py_ to use sqlite db
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
```
