### ISSUE TITLE
Problem when running the example 

### ISSUE THREAD

**Issue by i-bond** [zostera/django-bootstrap4#226]
Hello! I was trying to run the example project following the steps in [the instructions](https://github.com/zostera/django-bootstrap4/tree/main/example) and at first after using  `python manage.py migrate` I got the ModuleNotFoundError, [this thread](https://github.com/zostera/django-bootstrap4/issues/205) helped me to fix it, but not at all. When running `python manage.py runserver` it returns this;
`
Exception in thread django-main-thread:
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner self.run()
File "C:\ProgramData\Anaconda3\lib\threading.py", line 865, in run self._target(*self._args, **self._kwargs)
File "C:\ProgramData\Anaconda3\lib\site-packages\django\utils\autoreload.py", line 54, in wrapper  fn(*args, **kwargs) 
File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\management\commands\runserver.py", line 139, in inner_run ipv6=self.use_ipv6, threading=threading, server_cls=self.server_cls)
File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\servers\basehttp.py", line 203, in run  httpd = httpd_cls(server_address, WSGIRequestHandler, ipv6=ipv6)
File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\servers\basehttp.py", line 67, in __init__ super().__init__(*args, **kwargs)
File "C:\ProgramData\Anaconda3\lib\socketserver.py", line 452, in __init__self.server_bind()
File "C:\ProgramData\Anaconda3\lib\wsgiref\simple_server.py", line 50, in server_bind HTTPServer.server_bind(self)
File "C:\ProgramData\Anaconda3\lib\http\server.py", line 139, in server_bind self.server_name = socket.getfqdn(host)
File "C:\ProgramData\Anaconda3\lib\socket.py", line 676, in getfqdn hostname, aliases, ipaddrs = gethostbyaddr(name)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 0: invalid continuation byte`

Could you help me to find our what causes this error?

**Comment by i-bond** [comment]
My computer's name contained cyrillic characters, changing it to latin helped to fix this error, and now everything works fine :)
