### ISSUE TITLE
When I using demo with python manage.py runserver, it ends with django.core.exceptions.ImproperlyConfigured: Could not find the GDAL library (tr ied "gdal201", "gdal20", "gdal111", "gdal110", "gdal19"). Is GDAL installed? If it is, try setting GDAL_LIBRARY_PATH in your settings.

### ISSUE THREAD

**Issue by dollarzhaole** [zostera/django-bootstrap4#38]
django version: 1.11
python version: 3.6.1 x64
the traceback as follows:
`Unhandled exception in thread started by <function check_errors.<locals>.wrapper
 at 0x0000000003F592F0>
Traceback (most recent call last):
  File "C:\Users\dollar\AppData\Local\Programs\Python\Python36\lib\site-packages
\django\utils\autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\dollar\AppData\Local\Programs\Python\Python36\lib\site-packages
\django\core\management\commands\runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\dollar\AppData\Local\Programs\Python\Python36\lib\site-packages
\django\utils\autoreload.py", line 251, in raise_last_exception
    six.reraise(*_exception)
  File "C:\Users\dollar\AppData\Local\Programs\Python\Python36\lib\site-packages
\django\utils\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\dollar\AppData\Local\Programs\Python\Python36\lib\site-packages
\django\utils\autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\dollar\AppData\Local\Programs\Python\Python36\lib\site-packages
\django\__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\dollar\AppData\Local\Programs\Python\Python36\lib\site-packages
\django\apps\registry.py", line 116, in populate
    app_config.ready()
  File "C:\Users\dollar\AppData\Local\Programs\Python\Python36\lib\site-packages
\django\contrib\admin\apps.py", line 23, in ready
    self.module.autodiscover()
  File "C:\Users\dollar\AppData\Local\Programs\Python\Python36\lib\site-packages
\django\contrib\admin\__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "C:\Users\dollar\AppData\Local\Programs\Python\Python36\lib\site-packages
\django\utils\module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "C:\Users\dollar\AppData\Local\Programs\Python\Python36\lib\importlib\__i
nit__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\Users\dollar\AppData\Local\Programs\Python\Python36\lib\site-packages
\django\contrib\gis\admin\__init__.py", line 5, in <module>
    from django.contrib.gis.admin.options import GeoModelAdmin, OSMGeoAdmin
  File "C:\Users\dollar\AppData\Local\Programs\Python\Python36\lib\site-packages
\django\contrib\gis\admin\options.py", line 2, in <module>
    from django.contrib.gis.admin.widgets import OpenLayersWidget
  File "C:\Users\dollar\AppData\Local\Programs\Python\Python36\lib\site-packages
\django\contrib\gis\admin\widgets.py", line 3, in <module>
    from django.contrib.gis.gdal import GDALException
  File "C:\Users\dollar\AppData\Local\Programs\Python\Python36\lib\site-packages
\django\contrib\gis\gdal\__init__.py", line 28, in <module>
    from django.contrib.gis.gdal.datasource import DataSource
  File "C:\Users\dollar\AppData\Local\Programs\Python\Python36\lib\site-packages
\django\contrib\gis\gdal\datasource.py", line 39, in <module>
    from django.contrib.gis.gdal.driver import Driver
  File "C:\Users\dollar\AppData\Local\Programs\Python\Python36\lib\site-packages
\django\contrib\gis\gdal\driver.py", line 5, in <module>
    from django.contrib.gis.gdal.prototypes import ds as vcapi, raster as rcapi
  File "C:\Users\dollar\AppData\Local\Programs\Python\Python36\lib\site-packages
\django\contrib\gis\gdal\prototypes\ds.py", line 9, in <module>
    from django.contrib.gis.gdal.libgdal import GDAL_VERSION, lgdal
  File "C:\Users\dollar\AppData\Local\Programs\Python\Python36\lib\site-packages
\django\contrib\gis\gdal\libgdal.py", line 45, in <module>
    % '", "'.join(lib_names)
django.core.exceptions.ImproperlyConfigured: Could not find the GDAL library (tr
ied "gdal201", "gdal20", "gdal111", "gdal110", "gdal19"). Is GDAL installed? If
it is, try setting GDAL_LIBRARY_PATH in your settings.`

**Comment by dyve** [comment]
The demo uses some Django geom functions, and seems to require GDAL. Could you check if it's possible to catch and mitigate these errors in a PR?
